import type { INodeProperties, INodeTypeDescription, IWebhookDescription } from 'n8n-workflow';

import { getResponseCode, getResponseData } from '../utils/response';

const methods = ['DELETE', 'GET', 'HEAD', 'PATCH', 'POST', 'PUT'].map((method) => ({
	name: method,
	value: method,
}));

const webhookDescription: IWebhookDescription = {
	name: 'default',
	httpMethod: '={{$parameter["httpMethod"] || "GET"}}',
	isFullPath: true,
	responseCode: `={{(${getResponseCode})($parameter)}}`,
	responseMode: '={{$parameter["responseMode"]}}',
	responseData: `={{(${getResponseData})($parameter)}}`,
	responseBinaryPropertyName: '={{$parameter["responseBinaryPropertyName"]}}',
	responseContentType: '={{$parameter["options"]["responseContentType"]}}',
	responsePropertyName: '={{$parameter["options"]["responsePropertyName"]}}',
	responseHeaders: '={{$parameter["options"]["responseHeaders"]}}',
	path: '={{$parameter["path"]}}',
};

const validationProperties: INodeProperties[] = [
	{
		displayName: 'Validate Request Body',
		name: 'validateBody',
		type: 'boolean',
		default: true,
		description: 'Whether to validate the request body before starting the workflow',
	},
	{
		displayName: 'Schema Source',
		name: 'schemaSource',
		type: 'options',
		default: 'fields',
		options: [
			{ name: 'Define Fields Below', value: 'fields' },
			{ name: 'JSON Schema', value: 'json' },
		],
		displayOptions: { show: { validateBody: [true] } },
		description: 'How to define the JSON Schema used to validate request bodies',
	},
	{
		displayName: 'Schema Fields',
		name: 'schemaFields',
		type: 'fixedCollection',
		placeholder: 'Add Field',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { validateBody: [true], schemaSource: ['fields'] } },
		options: [
			{
				displayName: 'Field',
				name: 'values',
				values: [
					{
						displayName: 'Allowed Values',
						name: 'enumValues',
						type: 'json',
						default: '',
						placeholder: '["active", "inactive"]',
						description: 'Optional JSON array containing the only accepted values',
					},
					{
						displayName: 'Name',
						name: 'name',
						type: 'string',
						default: '',
						required: true,
						placeholder: 'email',
						description: 'Name of the property in the request body',
					},
					{
						displayName: 'Nullable',
						name: 'nullable',
						type: 'boolean',
						default: false,
						description: 'Whether the property may be null',
					},
					{
						displayName: 'Required',
						name: 'required',
						type: 'boolean',
						default: false,
						description: 'Whether the property must be present',
					},
					{
						displayName: 'Type',
						name: 'type',
						type: 'options',
						default: 'string',
						options: [
							{
								name: 'Array',
								value: 'array',
							},
							{
								name: 'Boolean',
								value: 'boolean',
							},
							{
								name: 'Integer',
								value: 'integer',
							},
							{
								name: 'Number',
								value: 'number',
							},
							{
								name: 'Object',
								value: 'object',
							},
							{
								name: 'String',
								value: 'string',
							},
						],
						description: 'JSON type required for this property',
					},
					{
						displayName: 'Validation Options',
						name: 'options',
						type: 'collection',
						default: {},
						placeholder: 'Add Option',
						options: [
							{
								displayName: 'Format',
								name: 'format',
								type: 'string',
								default: '',
								placeholder: 'email',
								description: 'AJV format such as email, date-time, URI, or UUID',
							},
							{
								displayName: 'Maximum',
								name: 'maximum',
								type: 'number',
								default: 0,
								description: 'Maximum accepted numeric value',
							},
							{
								displayName: 'Maximum Items',
								name: 'maxItems',
								type: 'number',
								default: 1,
								description: 'Maximum number of items in an array',
							},
							{
								displayName: 'Maximum Length',
								name: 'maxLength',
								type: 'number',
								default: 1,
								description: 'Maximum string length',
							},
							{
								displayName: 'Minimum',
								name: 'minimum',
								type: 'number',
								default: 0,
								description: 'Minimum accepted numeric value',
							},
							{
								displayName: 'Minimum Items',
								name: 'minItems',
								type: 'number',
								default: 1,
								description: 'Minimum number of items in an array',
							},
							{
								displayName: 'Minimum Length',
								name: 'minLength',
								type: 'number',
								default: 1,
								description: 'Minimum string length',
							},
							{
								displayName: 'Nested Schema',
								name: 'nestedSchema',
								type: 'json',
								default: '',
								placeholder: "{'items':{'type':'string'}}",
								description: 'JSON Schema keywords to merge into this field schema',
							},
							{
								displayName: 'Pattern',
								name: 'pattern',
								type: 'string',
								default: '',
								placeholder: '^[A-Za-z]+$',
								description: 'Regular expression that string values must match',
							},
							{
								displayName: 'Unique Items',
								name: 'uniqueItems',
								type: 'boolean',
								default: false,
								description: 'Whether array items must be unique',
							},
						],
					},
				],
			},
		],
		description: 'Fields used to build an object JSON Schema',
	},
	{
		displayName: 'JSON Schema',
		name: 'jsonSchema',
		type: 'json',
		default: '{\n  "type": "object",\n  "properties": {}\n}',
		displayOptions: { show: { validateBody: [true], schemaSource: ['json'] } },
		description: 'Complete JSON Schema used by AJV',
	},
	{
		displayName: 'Schema Options',
		name: 'schemaOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { validateBody: [true], schemaSource: ['fields'] } },
		options: [
			{
				displayName: 'Allow Additional Properties',
				name: 'additionalProperties',
				type: 'boolean',
				default: true,
				description: 'Whether properties not defined above are accepted',
			},
		],
	},
	{
		displayName: 'AJV Options',
		name: 'ajvOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { validateBody: [true] } },
		options: [
			{
				displayName: 'Coerce Types',
				name: 'coerceTypes',
				type: 'boolean',
				default: false,
				description: 'Whether AJV may convert scalar values to the required types',
			},
			{
				displayName: 'Collect All Errors',
				name: 'allErrors',
				type: 'boolean',
				default: true,
				description:
					'Whether to return every validation error instead of stopping at the first',
			},
			{
				displayName: 'Remove Additional Properties',
				name: 'removeAdditional',
				type: 'options',
				default: false,
				options: [
					{ name: 'Do Not Remove', value: false },
					{ name: 'Remove All', value: 'all' },
					{ name: 'Remove Failing', value: 'failing' },
				],
				description: 'Whether AJV removes properties not allowed by the schema',
			},
			{
				displayName: 'Strict Mode',
				name: 'strict',
				type: 'boolean',
				default: false,
				description: 'Whether AJV treats ignored or ambiguous schema constructs as errors',
			},
			{
				displayName: 'Use Defaults',
				name: 'useDefaults',
				type: 'boolean',
				default: false,
				description: 'Whether AJV inserts default values from the schema into the request body',
			},
			{
				displayName: 'Validate Formats',
				name: 'validateFormats',
				type: 'boolean',
				default: true,
				description:
					'Whether to validate standard formats such as email, URI, UUID, and date-time',
			},
		],
	},
	{
		displayName: 'Validation Error Status',
		name: 'validationErrorCode',
		type: 'number',
		default: 400,
		typeOptions: { minValue: 400, maxValue: 499 },
		displayOptions: { show: { validateBody: [true] } },
		description: 'HTTP status code returned when validation fails',
	},
];

const options: INodeProperties = {
	displayName: 'Options',
	name: 'options',
	type: 'collection',
	placeholder: 'Add Option',
	default: {},
	options: [
		{
			displayName: 'Field Name for Binary Data',
			name: 'binaryPropertyName',
			type: 'string',
			default: 'data',
			description: 'Name of the output field used for received binary data',
		},
		{
			displayName: 'Ignore Bots',
			name: 'ignoreBots',
			type: 'boolean',
			default: false,
			description: 'Whether to reject common link previewers and web crawlers',
		},
		{
			displayName: 'IP(s) Allowlist',
			name: 'ipWhitelist',
			type: 'string',
			default: '',
			placeholder: '127.0.0.1, 192.168.1.0/24',
			description: 'Comma-separated IP addresses or CIDR ranges allowed to call this endpoint',
		},
		{
			displayName: 'No Response Body',
			name: 'noResponseBody',
			type: 'boolean',
			default: false,
			displayOptions: { show: { '/responseMode': ['onReceived'] } },
			description: 'Whether to omit the response body',
		},
		{
			displayName: 'Only Run If',
			name: 'onlyRunIf',
			type: 'string',
			default: '',
			placeholder: "={{ $json.body.event === 'order.created' }}",
			description:
				'Expression that must return true to start the workflow; non-matching requests receive an empty response',
		},
		{
			displayName: 'Raw Body',
			name: 'rawBody',
			type: 'boolean',
			default: false,
			description: 'Whether to include the raw request body as binary data',
		},
		{
			displayName: 'Response Code',
			name: 'responseCode',
			type: 'number',
			default: 200,
			typeOptions: { minValue: 100, maxValue: 599 },
			displayOptions: { hide: { '/responseMode': ['responseNode'] } },
			description: 'HTTP status code to return',
		},
		{
			displayName: 'Response Content-Type',
			name: 'responseContentType',
			type: 'string',
			default: '',
			placeholder: 'application/json',
			description: 'Custom Content-Type header for the response',
		},
		{
			displayName: 'Response Data',
			name: 'responseData',
			type: 'string',
			default: '',
			displayOptions: { show: { '/responseMode': ['onReceived'] } },
			description: 'Custom response body returned immediately',
		},
		{
			displayName: 'Response Headers',
			name: 'responseHeaders',
			type: 'fixedCollection',
			typeOptions: { multipleValues: true },
			placeholder: 'Add Response Header',
			default: {},
			options: [
				{
					displayName: 'Header',
					name: 'entries',
					values: [
						{
							displayName: 'Name',
							name: 'name',
							type: 'string',
							default: '',
							description: 'Response header name',
						},
						{
							displayName: 'Value',
							name: 'value',
							type: 'string',
							default: '',
							description: 'Response header value',
						},
					],
				},
			],
			description: 'Headers to add to the webhook response',
		},
		{
			displayName: 'Response Property Name',
			name: 'responsePropertyName',
			type: 'string',
			default: 'data',
			displayOptions: {
				show: { '/responseMode': ['lastNode'], '/responseData': ['firstEntryJson'] },
			},
			description: 'Property to return instead of the complete JSON object',
		},
	],
};

export const restApiCredentials: INodeTypeDescription['credentials'] = [
	{
		name: 'restApiBasicAuthApi',
		required: true,
		displayOptions: { show: { authentication: ['basicAuth'] } },
	},
	{
		name: 'restApiHeaderAuthApi',
		required: true,
		displayOptions: { show: { authentication: ['headerAuth'] } },
	},
	{
		name: 'restApiJwtAuthApi',
		required: true,
		displayOptions: { show: { authentication: ['jwtAuth'] } },
	},
];

export const restApiWebhooks = [webhookDescription];

export const restApiProperties: INodeProperties[] = [
	{
		displayName: 'Allow Multiple HTTP Methods',
		name: 'multipleMethods',
		type: 'boolean',
		default: false,
		isNodeSetting: true,
		description: 'Whether to listen for more than one HTTP method',
	},
	{
		displayName: 'HTTP Method',
		name: 'httpMethod',
		type: 'options',
		options: methods,
		default: 'GET',
		displayOptions: { show: { multipleMethods: [false] } },
		description: 'HTTP method to listen for',
	},
	{
		displayName: 'HTTP Methods',
		name: 'httpMethod',
		type: 'multiOptions',
		options: methods,
		default: ['GET', 'POST'],
		displayOptions: { show: { multipleMethods: [true] } },
		description: 'HTTP methods to listen for',
	},
	{
		displayName: 'Path',
		name: 'path',
		type: 'string',
		default: '',
		placeholder: 'orders/:orderId',
		description: 'Path to listen on; use a colon prefix for dynamic segments',
	},
	{
		displayName: 'Authentication',
		name: 'authentication',
		type: 'options',
		options: [
			{ name: 'Basic Auth', value: 'basicAuth' },
			{ name: 'Header Auth', value: 'headerAuth' },
			{ name: 'JWT Auth', value: 'jwtAuth' },
			{ name: 'None', value: 'none' },
		],
		default: 'none',
		noDataExpression: true,
		description: 'Authentication required for inbound requests',
	},
	{
		displayName: 'Respond',
		name: 'responseMode',
		type: 'options',
		options: [
			{ name: 'Immediately', value: 'onReceived', description: 'As soon as this node runs' },
			{
				name: 'When Last Node Finishes',
				value: 'lastNode',
				description: 'With data from the last executed node',
			},
			{
				name: "Using 'Respond to Webhook' Node",
				value: 'responseNode',
				description: 'With the response defined in that node',
			},
			{
				name: 'Streaming',
				value: 'streaming',
				description: 'In real time from streaming-enabled nodes',
			},
		],
		default: 'onReceived',
		description: 'When and how to respond to the request',
	},
	{
		displayName: 'Response Data',
		name: 'responseData',
		type: 'options',
		default: 'firstEntryJson',
		displayOptions: { show: { responseMode: ['lastNode'] } },
		options: [
			{ name: 'All Entries', value: 'allEntries' },
			{ name: 'First Entry Binary', value: 'firstEntryBinary' },
			{ name: 'First Entry JSON', value: 'firstEntryJson' },
			{ name: 'No Response Body', value: 'noData' },
		],
		description: 'Data to return after the workflow finishes',
	},
	{
		displayName:
			'Connect a Respond to Webhook node to control the response later in the workflow.',
		name: 'responseNodeNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { responseMode: ['responseNode'] } },
	},
	{
		displayName: 'Connect a streaming-enabled node to send its output while the workflow runs.',
		name: 'streamingNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { responseMode: ['streaming'] } },
	},
	{
		displayName: 'Property Name',
		name: 'responseBinaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		displayOptions: { show: { responseData: ['firstEntryBinary'] } },
		description: 'Binary property to return',
	},
	...validationProperties,
	options,
];
